version: '3'

services:
  web:
    image: python:alpine
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "pip install -r requirements.txt 
      && flask --app server run -p 8000 --host=0.0.0.0"
